### ISSUE TITLE
Clean up lib folder

### ISSUE THREAD

**Issue by allenjhuang** [rorochaudhary/just-get-me-by#8]
Right now the lib folder contains algo/algo.py, api/api.py, and gui/gui.py. The extra folder layers seem a bit unnecessary and redundant.

This makes any imports of those files look like:
```
import lib.algo.algo
import lib.api.api
import lib.gui.gui
```

It's my fault for setting it up this way, but we should probably:
1) Get rid of the extra folder layers.
2) Modify any existing files to reflect the change.

**Comment by mchen1235** [comment]
Yeah, I agree with this since each folder has a file with the exact same name +.py.

**Comment by 96RadhikaJadhav** [comment]
Is this issue still available or already solved?

**Comment by allenjhuang** [comment]
Hi Radhika, this issue is already solved. Thanks for checking!
